name: fuzzysearch
description: Fuzzy search algorithm
version: 2.0.0
homepage: https://github.com/tomasweigenast/fuzzysearch

environment:
  sdk: "^3.0.0"

dev_dependencies:
  lint: ^2.0.0
  test: ^1.16.0
