name: fuzzysearch
description: Port of https://github.com/farzher/fuzzysort for Dart
version: 1.0.0
homepage: https://github.com/tomasweigenast/fuzzysearch

environment:
  sdk: '>=2.16.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
